name: Build and Publish
on:
  push:
    branches:
      - main

env:
  IMAGE_VERSION: ${{ github.run_number }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.IMAGE_VERSION }}

      - name: Build and tag Docker image
        run: |
          docker build -t your-username/your-image-name:${{ env.IMAGE_VERSION }} .
          docker push your-username/your-image-name:${{ env.IMAGE_VERSION }}

      - name: Publish new release
